# 81 descriptor vocabulary for matching
# Auto-generated from database - DO NOT EDIT MANUALLY
# To update: run the database query and regenerate this file

DESCRIPTORS = [
    "apple",
    "apricot",
    "astringent",
    "baking spice",
    "barrel",
    "berry",
    "black pepper",
    "bread",
    "brown sugar",
    "burnt",
    "butter",
    "butterscotch",
    "caramel",
    "caramel apple",
    "cedar",
    "cereal",
    "char",
    "charred",
    "cherry",
    "chocolate",
    "cinnamon",
    "citrus",
    "clove",
    "cocoa",
    "coffee",
    "corn",
    "cream",
    "dark chocolate",
    "dried fruit",
    "dry",
    "earth",
    "earthy",
    "ethanol",
    "floral",
    "fresh oak",
    "fruit",
    "ginger",
    "gingerbread",
    "grain",
    "grape",
    "grass",
    "hay",
    "heat",
    "honey",
    "leather",
    "lemon",
    "malt",
    "maple",
    "mint",
    "molasses",
    "mushroom",
    "nut",
    "nutmeg",
    "oak",
    "orange",
    "peach",
    "pear",
    "pecan",
    "pepper",
    "peppery heat",
    "pine",
    "plum",
    "raisin",
    "rich",
    "roasted",
    "rye",
    "smoke",
    "smooth",
    "spice",
    "stone fruit",
    "sugar",
    "sweet",
    "tannic",
    "toasted",
    "toasted grain",
    "toasted oak",
    "tobacco",
    "toffee",
    "tropical",
    "vanilla",
    "walnut",
]
